### PR TITLE
Update dependencies and complete rfc2202 test coverage.

### PR DESCRIPTION
**Pull request by pantsman0**
Update sha1 to 0.10, change rustc-serialize to hex 0.4.3

This also adds additional RFC test vectors.

### CODE REVIEW

**Comment by werdahias** [comment]
hi, any ETA on this MR ?

**Comment by werdahias** [comment]
awesome, thanks !

**Comment by pantsman0** [comment]
@werdahias merged. Check the lib.rs now though to see if you still want to use it. The reason I've sat on this for so long is that I will probably push a deprecation message into crates.io since this is now just a library of 3LoC from the RustCrypto project.

**Comment by werdahias** [comment]
@pantsman0 ah, ok. the reason I asked is because stun_codec depends on your crate and I wanted to package stund-codec for debian. I'll ping the stun-codec maintainers to use a different implementation then.

**Comment by pantsman0** [comment]
@werdahias I have opened [PR 20](https://github.com/sile/stun_codec/pull/20) in stun-codec to remove the dependency.

**Pull request merged**
